### ISSUE TITLE
About cl train

### ISSUE THREAD

**Issue by liwei1101** [BinhuiXie/SPCL#6]

**Comment by liwei1101** [comment]
Here I go again.

I recently ran into a problem while performing the step of contrast learning training and I hope you can clear up this confusion for me.

The question is that when I perform contrast learning training, I notice that there is almost no drop in contrast learning loss, is this normal?

**Comment by BinhuiXie** [comment]
Hi @liwei1101,

The reason may be that there are many pixels involved in the calculation of this pixel-level contrastive loss, so perhaps you can explore hard positive and hard negative pairs, which is important in traditional contrastive learning.

**Comment by liwei1101** [comment]
Hi @BinhuiXie ,
Thank you for your prompt response!

But I didn't quite understand what you meant. It means that the contrast learning loss should decrease with normal training, right?

Yes. This does require a large amount of computation, so what should I do? What do you mean by "explore hard positive and hard negative pairs"?

**Comment by BinhuiXie** [comment]
It is normal that the pixel-level contrastive loss is stable in our situation.

And it is the future work to explore the hard positive and hard negative pairs to reduce computing demands.

**Comment by liwei1101** [comment]
OK! Thank you for your prompt reply!

Looking forward to your future work!

**Comment by BinhuiXie** [comment]
Together for the future!
